name: CI Pipeline (Flask + SQL Server + Cypress)

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  test-and-verify:
    runs-on: ubuntu-latest

    services:
      mssql:
        image: mcr.microsoft.com/mssql/server:2022-latest
        env:
          ACCEPT_EULA: "Y"
          MSSQL_SA_PASSWORD: "Strong_Pass_123!" 
        ports:
          - 1433:1433
        options: >-
          --health-cmd "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'Strong_Pass_123!' -Q 'SELECT 1' -C"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install SQL Server ODBC Drivers (Linux)
        run: |
          sudo apt-get update
          sudo apt-get install -y unixodbc-dev
          curl https://packages.microsoft.com/keys/microsoft.asc | sudo tee /etc/apt/trusted.gpg.d/microsoft.asc
          curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
          sudo apt-get update
          sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask pyodbc python-dotenv

      - name: Create temporary .env file
        run: |
          echo "SERVER=localhost" >> .env
          echo "DATABASE=tempdb" >> .env
          echo "UID=sa" >> .env
          echo "PWD=Strong_Pass_123!" >> .env
          echo "TABLE=colaboradores" >> .env

      - name: Wait for SQL Server to be ready
        run: |
          docker ps -a
          until nc -z -v -w30 localhost 1433; do
            echo "Esperando a que SQL Server responda en el puerto 1433..."
            sleep 5
          done

      - name: Start Flask App
        run: |
          python ./app/app.py &
        env:
          FLASK_ENV: testing

      - name: Run Cypress Tests
        uses: cypress-io/github-action@v6
        with:
          wait-on: 'http://127.0.0.1:5000'
          wait-on-timeout: 60